# Generated by Django 4.1.5 on 2023-01-23 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "keyword",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "search_link",
                    models.URLField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid linkedin search link",
                                regex="^https://www\\.linkedin\\.com/search/results/content/\\?keywords=.+",
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Search Keywords",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LatestPost",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("posted_at", models.DateTimeField()),
                ("body", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="linkedin_sworker.searchkeyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="latestpost",
            index=models.Index(
                fields=["posted_at"], name="linkedin_sw_posted__87bb55_idx"
            ),
        ),
    ]
