# Generated by Django 4.1.5 on 2023-01-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin_sworker", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SearchKeyword",
            new_name="SearchLink",
        ),
    ]
