# Generated by Django 4.1.5 on 2023-01-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin_sworker", "0002_rename_searchkeyword_searchlink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="latestpost",
            old_name="keyword",
            new_name="search_link",
        ),
    ]
