# Generated by Django 4.1.5 on 2023-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin_sworker", "0003_rename_keyword_latestpost_search_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "search_links",
                    models.ManyToManyField(
                        related_name="subscriptions", to="linkedin_sworker.searchlink"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Update Subscriptions",
                "ordering": ("-created_at",),
            },
        ),
    ]
