# Generated by Django 4.1.5 on 2023-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin_sworker", "0004_updatesubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatesubscription",
            name="search_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to="linkedin_sworker.searchlink",
            ),
        ),
    ]
