# Generated by Django 4.1.5 on 2023-01-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin_sworker", "0005_alter_updatesubscription_search_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchlink",
            options={
                "ordering": ("-created_at",),
                "verbose_name_plural": "Search Links",
            },
        ),
    ]
